# Specify a different separator for branch names

version: 2
updates:
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'weekly'
    pull-request-branch-name:
      separator: '-'
