version: 2

multi-ecosystem-groups:
  security:
    schedule:
      interval: 'daily'
    open-pull-requests-limit: 0 # disables version-update PRs; security PRs unaffected
    pull-request-branch-name:
      separator: '-'

updates:
  - package-ecosystem: 'bundler'
    directory: '/'
    patterns: ['*']
    multi-ecosystem-group: 'security'

  - package-ecosystem: 'github-actions'
    directory: '/'
    patterns: ['*']
    multi-ecosystem-group: 'security'
